import {Config} from 'tailwindcss';

const config: Config = {
    content: [
        './src/**/*.{ts,tsx}', // Scan TypeScript and TSX files in src
    ],
    theme: {
        extend: {
            colors: {
                'creator-black': '#010101',
                'true-blue': '#0659D8',
                'vampire-black': '#070505',
                'smoky-black': '#0E0E0E',
                'chinese-black': '#111111',
                'raisin-black': '#222222',
                'dark-charcoal': '#333333',
                'outer-space': '#444444',
                'jelly-bean-blue': '#457F97',
                zomp: '#45A580',
                'ultramarine-blue': '#475FF7',
                turquoise: '#47D7F7',
                'granite-gray': '#666666',
                'bud-green': '#78AD51',
                'taupe-gray': '#888888',
                'spanish-gray': '#999999',
                'shiny-shamrock': '#4FA580',
                purple: '#A328FF',
                'acid-green': '#B9B51F',
                'medium-violet-red': '#B2088A',
                'light-pastel-purple': '#B7A1DD',
                'steel-pink': '#CB2AC0',
                'chinese-silver': '#CCCCCC',
                'electric-lime': '#CCFF00',
                persimmon: '#E64F00',
                'royal-orange': '#EA9746',
                crayola: '#EBB6D2',
                maize: '#EEC655',
                'rose-pink': '#F670DB',
                'international-orange': '#FF4C01',
                'lemon-yellow': '#FCED4A',
                'red-orange': '#FF4601',
                'persian-pink': '#FF75BF',
                'princess-perfume': '#FC88CA',
                'naples-yellow': '#FFDC5F',
                'radical-red': '#FF2B6C',
                'united-nations-blue': '#627EEA',
                'lavender-indigo': '#8247E5',
                white: '#FFFFFF',
                'forest-green': '#004E1D',
                'june-bud': '#A5DB4E',
                'tufts-blue': '#4583DC',
                'st-patrick-blue': '#15297A',
                'cornflower-blue': '#6D81E4',
                'light-cobalt-blue': '#899AE9',
                coinbase: '#1652F0',
                'blue-violet': '#7A40E5',
                'dark-orchid': '#992FCE',
                'tezos-blue': '#709AFF',
                'blue-crayola': '#2D7DF8',
                'japanese-indigo': '#2E374B',
                'lapis-lazuli': '#2C6593',
                'cyan-azure': '#4D81AA',
                rudy: '#FF0420',
                'dark-candy-apple-red': '#A60000',
                'blue-base': '#033DFF',
                lavender: '#E5EAFC',
                'audius-1': '#CC0FE0',
                'audius-2': '#7E1BCC',
                'audius-3': '#2C0F93',
                'showtime-1': '#C8820E',
                'showtime-2': '#EFA61D',
                'showtime-3': '#FACE52',
                'showtime-4': '#FBF6D3',
                'friendtech-1': '#2ECFF6',
                'friendtech-2': '#7059FB',
                'friendtech-3': '#AC50EF',
                'soundxyz-1': '#DE32A6',
                'soundxyz-2': '#3A2339',
                'soundxyz-3': '#37677E',
                'zora-1': '#FFEEF8',
                'zora-2': '#E3C5EA',
                'zora-3': '#6483E6',
                'zora-4': '#3C6EE4',
                'zora-5': '#3967D7',
                'zora-6': '#261118',
                'zora-7': '#7F4E2C',
                'plump-purple': '#673EBB',
                fandango: '#A83C96',
                ruber: '#DC4974',
                'sandy-brown': '#E89D60',
                'rainbow-1': '#881AB3',
                'rainbow-2': '#E433D3',
                'rainbow-3': '#E9642C',
                'rainbow-4': '#F4E24B',
                'rainbow-5': '#6EED47',
                'rainbow-6': '#6BE6C6',
                'rainbow-7': '#23567F',
                'trust-1': '#2C63BF',
                'trust-2': '#295BA8',
                walletconnect: '#5095F7',
                'avalanche-1': '#EB2C2E',
                'avalanche-2': '#B13232',
                'poap-1': '#B5AEFF',
                'poap-2': '#5E58A5',
                discord: '#7289da',
                'dark-pink': '#EE1D52',
                'mirror-1': '#E0F1FF',
                'mirror-2': '#0A7CFF',
                'mirror-3': '#007AFF',
                'farcaster-1': '#8A63D2',
                'farcaster-2': '#835DC4',
                'blast-1': '#FCFC03',
                'blast-2': '#FCFDC7',
            },
            backgroundColor: ({theme}) => ({
                ...theme('colors'),
            }),
            borderColor: ({theme}) => ({
                ...theme('colors'),
            }),
            textColor: ({theme}) => ({
                ...theme('colors'),
            }),
            borderRadius: {
                input: '2px',
                standard: '5px',
                extreme: '9rem',
            },
            dropShadow: {
                'creator-white': '0 0 5px rgba(255, 255, 255, 0.5)',
                'creator-red': '0 0 5px rgba(255, 76, 1, 0.5)',
                'creator-yellow': '0 0 5px rgba(237, 201, 82, 0.5)',
                'creator-blue': '0 0 5px rgba(76, 96, 246, 0.5)',
                'creator-green': '0 0 5px rgba(69, 127, 151, 0.5)',
                'creator-pink': '0 0 5px rgba(255, 117, 191, 0.5)',
            },
            boxShadow: {
                'creator-white': '0 0 5px rgba(255, 255, 255, 0.5)',
                'creator-red': '0 0 5px rgba(255, 76, 1, 0.5)',
                'creator-yellow': '0 0 5px rgba(237, 201, 82, 0.5)',
                'creator-blue': '0 0 5px rgba(76, 96, 246, 0.5)',
                'creator-green': '0 0 5px rgba(69, 127, 151, 0.5)',
                'creator-pink': '0 0 5px rgba(255, 117, 191, 0.5)',
                'form-control': `0 0 0 2px #010101 inset`,
            },
            flex: {
                2: '2 2 0%',
                3: '3 3 0%',
            },
            fontSize: {
                lg: '1.16rem',
                'primary-button': '0.875rem',
                '3xl': '2rem',
            },
            fontFamily: {
                brik: ['BT Brik XXL', 'sans-serif'],
                'du-bois': ['VTC Du Bois', 'sans-serif'],
                'apercu-mono': ['ApercuMono', 'sans-serif'],
            },
            letterSpacing: {
                wider: '.15em',
                widest: '.35em',
                lol: '-.01em',
            },
            lineHeight: {
                11: '2.75rem',
            },
            zIndex: {
                overlay: '50',
            },
            gridTemplateColumns: {
                '2-noshrink': 'repeat(2, 1fr)',
            },
        },
    },
    safelist: [
        // P00ls Gradients
        'bg-gradient-to-r from-electric-lime from-[0.38%] to-maize to-[98.58%]',
        'bg-gradient-to-r hover:from-electric-lime hover:from-[0.38%] group-hover:from-electric-lime group-hover:from-[0.38%] hover:to-maize hover:to-[98.58%] group-hover:to-maize group-hover:to-[98.58%]',
        'bg-gradient-to-r from-international-orange from-[-9.42%] to-persian-pink to-[108.76%]',
        'bg-gradient-to-r hover:from-international-orange hover:from-[-9.42%] group-hover:from-international-orange group-hover:from-[-9.42%] hover:to-persian-pink hover:to-[108.76%] group-hover:to-persian-pink group-hover:to-[108.76%]',
        'bg-gradient-to-r from-persian-pink from-[0.38%] to-maize to-[98.58%]',
        'bg-gradient-to-r hover:from-persian-pink hover:from-[0.38%] group-hover:from-persian-pink group-hover:from-[0.38%] hover:to-maize hover:to-[98.58%] group-hover:to-maize group-hover:to-[98.58%]',
        'bg-gradient-to-r from-acid-green from-[0.38%] to-maize to-[98.58%]',
        'bg-gradient-to-r hover:from-acid-green hover:from-[0.38%] group-hover:from-acid-green group-hover:from-[0.38%] hover:to-maize hover:to-[98.58%] group-hover:to-maize group-hover:to-[98.58%]',
        'bg-gradient-to-r from-true-blue from-[0.81%] to-lemon-yellow to-[112.7%]',
        'bg-gradient-to-r hover:from-true-blue hover:from-[0.81%] group-hover:from-true-blue group-hover:from-[0.81%] hover:to-lemon-yellow hover:to-[112.7%] group-hover:to-lemon-yellow group-hover:to-[112.7%]',
        'bg-gradient-to-r from-bud-green from-[0.81%] to-royal-orange to-[112.7%]',
        'bg-gradient-to-r hover:from-bud-green hover:from-[0.81%] group-hover:from-bud-green group-hover:from-[0.81%] hover:to-royal-orange hover:to-[112.7%] group-hover:to-royal-orange group-hover:to-[112.7%]',
        'bg-gradient-to-r from-purple from-[0.81%] to-radical-red to-[112.7%]',
        'bg-gradient-to-r hover:from-purple hover:from-[0.81%] group-hover:from-purple group-hover:from-[0.81%] hover:to-radical-red hover:to-[112.7%] group-hover:to-radical-red group-hover:to-[112.7%]',
        'bg-gradient-to-r from-princess-perfume from-[0.81%] to-crayola to-[112.7%]',
        'bg-gradient-to-r hover:from-princess-perfume hover:from-[0.81%] group-hover:from-princess-perfume group-hover:from-[0.81%] hover:to-crayola hover:to-[112.7%] group-hover:to-crayola group-hover:to-[112.7%]',
        'bg-gradient-to-r from-jelly-bean-blue from-[0.81%] to-zomp to-[112.7%]',
        'bg-gradient-to-r hover:from-jelly-bean-blue hover:from-[0.81%] group-hover:from-jelly-bean-blue group-hover:from-[0.81%] hover:to-zomp hover:to-[112.7%] group-hover:to-zomp group-hover:to-[112.7%]',
        'bg-gradient-to-r from-light-pastel-purple from-[0.81%] to-rose-pink to-[112.7%]',
        'bg-gradient-to-r hover:from-light-pastel-purple hover:from-[0.81%] group-hover:from-light-pastel-purple group-hover:from-[0.81%] hover:to-rose-pink hover:to-[112.7%] group-hover:to-rose-pink group-hover:to-[112.7%]',
        'bg-gradient-to-r from-persimmon from-[0.81%] to-medium-violet-red to-[112.7%]',
        'bg-gradient-to-r hover:from-persimmon hover:from-[0.81%] group-hover:from-persimmon group-hover:from-[0.81%] hover:to-medium-violet-red hover:to-[112.7%] group-hover:to-medium-violet-red group-hover:to-[112.7%]',
        'bg-gradient-to-r from-red-orange from-[0.81%] to-lemon-yellow to-[112.7%]',
        'bg-gradient-to-r hover:from-red-orange hover:from-[0.81%] group-hover:from-red-orange group-hover:from-[0.81%] hover:to-lemon-yellow hover:to-[112.7%] group-hover:to-lemon-yellow group-hover:to-[112.7%]',
        'bg-gradient-to-r from-persian-pink from-[-1.59%] to-international-orange to-[108.93%]',
        'bg-gradient-to-r hover:from-persian-pink hover:from-[-1.59%] group-hover:from-persian-pink group-hover:from-[-1.59%] hover:to-international-orange hover:to-[108.93%] group-hover:to-international-orange group-hover:to-[108.93%]',
        'bg-gradient-to-r from-ultramarine-blue from-[0.38%] to-persian-pink to-[98.58%]',
        'bg-gradient-to-r hover:from-ultramarine-blue hover:from-[0.38%] group-hover:from-ultramarine-blue group-hover:from-[0.38%] hover:to-persian-pink hover:to-[98.58%] group-hover:to-persian-pink group-hover:to-[98.58%]',
        'bg-gradient-to-br from-electric-lime from-[3.79%] to-turquoise to-[96.21%]',
        'bg-gradient-to-br hover:from-electric-lime hover:from-[3.79%] group-hover:from-electric-lime group-hover:from-[3.79%] hover:to-turquoise hover:to-[96.21%] group-hover:to-turquoise group-hover:to-[96.21%]',
        'bg-gradient-to-br from-plump-purple from-[-6.11%] via-fandango via-[38.46%] via-ruber via-[77.94%] to-sandy-brown to-[116.14%]',
        'bg-gradient-to-br hover:from-plump-purple hover:from-[-6.11%] group-hover:from-plump-purple group-hover:from-[-6.11%] hover:via-fandango hover:via-[38.46%] group-hover:via-fandango group-hover:via-[38.46%] hover:via-ruber hover:via-[77.94%] group-hover:via-ruber group-hover:via-[77.94%] hover:to-sandy-brown hover:to-[116.14%] group-hover:to-sandy-brown group-hover:to-[116.14%]',

        // Brand Gradients
        'bg-gradient-to-br from-cornflower-blue from-[7.48%] to-light-cobalt-blue to-[106.12%]',
        'bg-gradient-to-br hover:from-cornflower-blue hover:from-[7.48%] group-hover:from-cornflower-blue group-hover:from-[7.48%] hover:to-light-cobalt-blue hover:to-[106.12%] group-hover:to-light-cobalt-blue group-hover:to-[106.12%]',
        'bg-gradient-to-br from-blue-violet from-[7.48%] to-dark-orchid to-[106.12%]',
        'bg-gradient-to-br hover:from-blue-violet hover:from-[7.48%] group-hover:from-blue-violet group-hover:from-[7.48%] hover:to-dark-orchid hover:to-[106.12%] group-hover:to-dark-orchid group-hover:to-[106.12%]',
        'bg-gradient-to-br from-tezos-blue from-[-3.64%] to-blue-crayola to-[80.98%]',
        'bg-gradient-to-br hover:from-tezos-blue hover:from-[-3.64%] group-hover:from-tezos-blue group-hover:from-[-3.64%] hover:to-blue-crayola hover:to-[80.98%] group-hover:to-blue-crayola group-hover:to-[80.98%]',
        'bg-gradient-to-br from-japanese-indigo from-[-1.88%] via-lapis-lazuli via-[41.76%] to-cyan-azure to-[80.98%]',
        'bg-gradient-to-br hover:from-japanese-indigo hover:from-[-1.88%] group-hover:from-japanese-indigo group-hover:from-[-1.88%] hover:via-lapis-lazuli hover:via-[41.76%] group-hover:via-lapis-lazuli group-hover:via-[41.76%] hover:to-cyan-azure hover:to-[80.98%] group-hover:to-cyan-azure group-hover:to-[80.98%]',
        'bg-gradient-to-br from-rudy from-[7.48%] to-dark-candy-apple-red to-[106.12%]',
        'bg-gradient-to-br hover:from-rudy hover:from-[7.48%] group-hover:from-rudy group-hover:from-[7.48%] hover:to-dark-candy-apple-red hover:to-[106.12%] group-hover:to-dark-candy-apple-red group-hover:to-[106.12%]',
        'bg-gradient-to-l from-forest-green from-[-17.55%] to-june-bud to-[109.39%]',
        'bg-gradient-to-l hover:from-forest-green hover:from-[-17.55%] hover:to-june-bud hover:to-[109.39%]',
        'bg-gradient-to-br from-tufts-blue from-[-3.64%] to-st-patrick-blue to-[80.98%]',
        'bg-gradient-to-br hover:from-tufts-blue hover:from-[-3.64%] group-hover:from-tufts-blue group-hover:from-[-3.64%] hover:to-st-patrick-blue hover:to-[80.98%] group-hover:to-st-patrick-blue group-hover:to-[80.98%]',
        'bg-gradient-to-tl from-soundxyz-1 from-[-17.55%] via-soundxyz-2 via-[51.21%] to-soundxyz-3 to-[109.39%]',
        'bg-gradient-to-tl hover:from-soundxyz-1 hover:from-[-17.55%] group-hover:from-soundxyz-1 group-hover:from-[-17.55%] hover:via-soundxyz-2 hover:via-[51.21%] group-hover:via-soundxyz-2 group-hover:via-[51.21%] hover:to-soundxyz-3 hover:to-[109.39%] group-hover:to-soundxyz-3 group-hover:to-[109.39%]',
        'bg-gradient-to-r from-coinbase from-[0%] to-coinbase to-[100%]',
        'bg-gradient-to-r hover:from-coinbase hover:from-[0%] group-hover:from-coinbase group-hover:from-[0%] hover:to-coinbase hover:to-[100%] group-hover:to-coinbase group-hover:to-[100%]',
        'bg-gradient-to-r from-rainbow-1 from-[-1.98%] via-rainbow-2 via-[19.72%] via-rainbow-3 via-[36.54%] via-rainbow-4 via-[52.81%] via-rainbow-5 via-[71.79%] via-rainbow-6 via-[87.25%] to-rainbow-7 to-[102.17%]',
        'bg-gradient-to-r hover:from-rainbow-1 hover:from-[-1.98%] group-hover:from-rainbow-1 group-hover:from-[-1.98%] hover:via-rainbow-2 hover:via-[19.72%] group-hover:via-rainbow-2 group-hover:via-[19.72%] hover:via-rainbow-3 hover:via-[36.54%] group-hover:via-rainbow-3 group-hover:via-[36.54%] hover:via-rainbow-4 hover:via-[52.81%] group-hover:via-rainbow-4 group-hover:via-[52.81%] hover:via-rainbow-5 hover:via-[71.79%] group-hover:via-rainbow-5 group-hover:via-[71.79%] hover:via-rainbow-6 hover:via-[87.25%] group-hover:via-rainbow-6 group-hover:via-[87.25%] hover:to-rainbow-7 hover:to-[102.17%] group-hover:to-rainbow-7 group-hover:to-[102.17%]',
        'bg-gradient-to-r from-trust-1 from-[0%] to-trust-2 to-[110.01%]',
        'bg-gradient-to-r hover:from-trust-1 hover:from-[0%] group-hover:from-trust-1 group-hover:from-[0%] hover:to-trust-2 hover:to-[110.01%] group-hover:to-trust-2 group-hover:to-[110.01%]',
        'bg-gradient-to-r from-walletconnect from-[0%] to-walletconnect to-[100%]',
        'bg-gradient-to-r hover:from-walletconnect hover:from-[0%] group-hover:from-walletconnect group-hover:from-[0%] hover:to-walletconnect hover:to-[100%] group-hover:to-walletconnect group-hover:to-[100%]',
        'bg-gradient-to-bl from-audius-1 from-[17.41%] via-audius-2 via-[64.85%] to-audius-3 to-[94.09%]',
        'bg-gradient-to-bl hover:from-audius-1 hover:from-[17.41%] group-hover:from-audius-1 group-hover:from-[17.41%] hover:via-audius-2 hover:via-[64.85%] group-hover:via-audius-2 group-hover:via-[64.85%] hover:to-audius-3 hover:to-[94.09%] group-hover:to-audius-3 group-hover:to-[94.09%]',
        'bg-gradient-to-t from-showtime-1 from-[-0.97%] via-showtime-2 via-[27.22%] via-showtime-3 via-[64.78%] to-showtime-4 to-[89.43%]',
        'bg-gradient-to-t hover:from-showtime-1 hover:from-[-0.97%] group-hover:from-showtime-1 group-hover:from-[-0.97%] hover:via-showtime-2 hover:via-[27.22%] group-hover:via-showtime-2 group-hover:via-[27.22%] hover:via-showtime-3 hover:via-[64.78%] group-hover:via-showtime-3 group-hover:via-[64.78%] hover:to-showtime-4 hover:to-[89.43%] group-hover:to-showtime-4 group-hover:to-[89.43%]',
        'bg-gradient-to-bl from-friendtech-1 from-[7.46%] via-friendtech-2 via-[82.1%] to-friendtech-3 to-[98.92%]',
        'bg-gradient-to-bl hover:from-friendtech-1 hover:from-[7.46%] group-hover:from-friendtech-1 group-hover:from-[7.46%] hover:via-friendtech-2 hover:via-[82.1%] group-hover:via-friendtech-2 group-hover:via-[82.1%] hover:to-friendtech-3 hover:to-[98.92%] group-hover:to-friendtech-3 group-hover:to-[98.92%]',
        'bg-gradient-to-l from-blue-base from-[18.99%] to-lavender to-[104.17%]',
        'bg-gradient-to-l hover:from-blue-base hover:from-[18.99%] group-hover:from-blue-base group-hover:from-[18.99%] hover:to-lavender hover:to-[104.17%] group-hover:to-lavender group-hover:to-[104.17%]',
        'bg-gradient-to-bl from-zora-1 from-[14.5%] via-zora-2 via-[17.89%] via-zora-3 via-[24.5%] via-zora-4 via-[34.42%] via-zora-5 via-[48.24%] via-zora-6 via-[77.77%] to-zora-7 to-[92.97%]',
        'bg-gradient-to-bl hover:from-zora-1 hover:from-[14.5%] group-hover:from-zora-1 group-hover:from-[14.5%] hover:via-zora-2 hover:via-[17.89%] group-hover:via-zora-2 group-hover:via-[17.89%] hover:via-zora-3 hover:via-[24.5%] group-hover:via-zora-3 group-hover:via-[24.5%] hover:via-zora-4 hover:via-[34.42%] group-hover:via-zora-4 group-hover:via-[34.42%] hover:via-zora-5 hover:via-[48.24%] group-hover:via-zora-5 group-hover:via-[48.24%] hover:via-zora-6 hover:via-[77.77%] group-hover:via-zora-6 group-hover:via-[77.77%] hover:to-zora-7 hover:to-[92.97%] group-hover:to-zora-7 group-hover:to-[92.97%]',
        'bg-gradient-to-l from-blast-1 from-[7.48%] to-blast-2 to-[106.12%]',
        'bg-gradient-to-l hover:from-blast-1 hover:from-[7.48%] group-hover:from-blast-1 group-hover:from-[7.48%] hover:to-blast-2 hover:to-[106.12%] group-hover:to-blast-2 group-hover:to-[106.12%]',
        'bg-gradient-to-br from-avalanche-1 from-[12.87%] to-avalanche-2 to-[96%]',
        'bg-gradient-to-br hover:from-avalanche-1 hover:from-[12.87%] group-hover:from-avalanche-1 group-hover:from-[12.87%] hover:to-avalanche-2 hover:to-[96%] group-hover:to-avalanche-2 group-hover:to-[96%]',
        'bg-gradient-to-tr from-poap-1 from-[3.2%] to-poap-2 to-[94.91%]',
        'bg-gradient-to-tr hover:from-poap-1 hover:from-[3.2%] group-hover:from-poap-1 group-hover:from-[3.2%] hover:to-poap-2 hover:to-[94.91%] group-hover:to-poap-2 group-hover:to-[94.91%]',
        'bg-gradient-to-r from-mirror-1 from-[7.48%] via-mirror-2 via-[79.48%] to-mirror-3 to-[106.12%]',
        'bg-gradient-to-r hover:from-mirror-1 hover:from-[7.48%] group-hover:from-mirror-1 group-hover:from-[7.48%] hover:via-mirror-2 hover:via-[79.48%] group-hover:via-mirror-2 group-hover:via-[79.48%] hover:to-mirror-3 hover:to-[106.12%] group-hover:to-mirror-3 group-hover:to-[106.12%]',
        'bg-gradient-to-l from-farcaster-1 from-[7.48%] to-farcaster-2 to-[106.12%]',
        'bg-gradient-to-l hover:from-farcaster-1 hover:from-[7.48%] group-hover:from-farcaster-1 group-hover:from-[7.48%] hover:to-farcaster-2 hover:to-[106.12%] group-hover:to-farcaster-2 group-hover:to-[106.12%]'
    ],
    plugins: [],
};

export default config;
